/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uscs;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author guilherme
 */
public class ProdutoView extends javax.swing.JFrame implements ProdutoListener{

    /**
     * Creates new form ViewProduto
     */
    
    ProdutoController produtoController = ProdutoController.getInstance();
    ProdutoPattern produtoPattern = new ProdutoPattern();
    
    DefaultTableModel tableModel;
    
    public ProdutoView() {
        initComponents();
        
        tableBuscaProdutos.setRowSelectionAllowed(true);
        tableBuscaProdutos.setEnabled(true);
        editarLinhaSelecionada();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscaProdutoText = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        botaoNovo = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuscaProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Crud Produto");
        setLocation(new java.awt.Point(200, 200));

        jLabel1.setText("Selecione por id:");

        buscaProdutoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaProdutoTextActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        tableBuscaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Referência", "Marca", "Categoria", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableBuscaProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buscaProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoNovo)
                        .addGap(18, 18, 18)
                        .addComponent(botaoEditar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoExcluir)
                        .addGap(0, 58, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buscaProdutoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar)
                    .addComponent(botaoNovo)
                    .addComponent(botaoEditar)
                    .addComponent(botaoExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaProdutoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaProdutoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaProdutoTextActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        if(buscaProdutoText.getText().trim().isEmpty()) {
            tableModel = (DefaultTableModel) tableBuscaProdutos.getModel();
            tableModel.setNumRows(0);
            for (Produto produto : produtoController.getList()) {
                tableModel.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getReferencia(),
                produto.getMarca(),
                produto.getCategoria(),
                produtoPattern.formatarDoubleParaString(produto.getPreco())
                });
            }
        }
        
        else {
            tableModel = (DefaultTableModel) tableBuscaProdutos.getModel();
            tableModel.setNumRows(0);
            for (Produto produto : produtoController.getList()) {
                if(Integer.parseInt(buscaProdutoText.getText()) == produto.getId()) {
                    tableModel.addRow(new Object[]{
                    produto.getId(),
                    produto.getNome(),
                    produto.getReferencia(),
                    produto.getMarca(),
                    produto.getCategoria(),
                    produtoPattern.formatarDoubleParaString(produto.getPreco())
                    });
                }
            }
            
            }
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        CadastroProduto obj = new CadastroProduto(this, true, this);
        obj.setVisible(true);
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        Produto produto = produtoController.obterProdutoPorId(Integer.parseInt(buscaProdutoText.getText()));
        if (produto != null) {
            EditarProduto obj = new EditarProduto(this, true, this, produto);
            obj.setVisible(true);
            
        }
        
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza que seja excluir este produto?",
                                                    "Confirmação de exclusão",
                                                    JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
                Iterator<Produto> iterator = produtoController.getList().iterator();
                
                while(iterator.hasNext()) {
                    Produto produto = iterator.next();
                     if (produto.getId() == Integer.parseInt(buscaProdutoText.getText())) {
                        iterator.remove(); // Remove o elemento de maneira segura
                    }       
                }
                tableModel = (DefaultTableModel) tableBuscaProdutos.getModel();
                tableModel.setNumRows(0);
        }
        else if (opcao == JOptionPane.NO_OPTION) {
            tableModel = (DefaultTableModel) tableBuscaProdutos.getModel();
            tableModel.setNumRows(0);
            for (Produto produto : produtoController.getList()) {
                if(Integer.parseInt(buscaProdutoText.getText()) == produto.getId()) {
                    tableModel.addRow(new Object[]{
                    produto.getId(),
                    produto.getNome(),
                    produto.getReferencia(),
                    produto.getMarca(),
                    produto.getCategoria(),
                    produto.getPreco()
                    });
                }
            }
        }
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    
    private void editarLinhaSelecionada() {
        tableBuscaProdutos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int linhaSelecionada = tableBuscaProdutos.getSelectedRow();
                    handleTableClick(linhaSelecionada);
                }
            }

            private void handleTableClick(int linhaSelecionada) {
               Object idObj = tableBuscaProdutos.getValueAt(linhaSelecionada, 0);
            
            if (idObj instanceof Integer) {
                int idProduto = (int) idObj;
                Produto produto = produtoController.obterProdutoPorId(idProduto);
                
                if (produto != null) {
                    EditarProduto obj = new EditarProduto(ProdutoView.this, true, ProdutoView.this, produto);
                    obj.setVisible(true);
                }
            }
            }
        });
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JTextField buscaProdutoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBuscaProdutos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void produtoCadastrado(Produto produto) {
        tableModel = (DefaultTableModel) tableBuscaProdutos.getModel();
        tableModel.setNumRows(0);
        tableModel.addRow(new Object[]{
        produto.getId(),
        produto.getNome(),
        produto.getReferencia(),
        produto.getMarca(),
        produto.getCategoria(),
        produtoPattern.formatarDoubleParaString(produto.getPreco())
        });
    }
}
